TrainingApp/TrainingApp.Host/Controllers/GoodsController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TrainingApp.Business.Services.Base;
using TrainingApp.Data.Models.Goods;
using TrainingApp.Data.DTO.Goods;
using Microsoft.AspNetCore.Http;
using System.IO;
using ExcelDataReader;

namespace TrainingApp.Host.Controllers
{
    using IGoodsServ = IBaseService<GoodsListDTO, GoodsDetailDTO, Goods>;

    public class GoodsController : Controller
    {
        private readonly IGoodsServ goodsServ;

        public GoodsController(
            IGoodsServ goodsServ)
        {
            this.goodsServ = goodsServ;
        }

        public async Task<IActionResult> Index()
        {
            var goods = await goodsServ.GetListDTO().ToListAsync();
            return View(goods);
        }

        public async Task<IActionResult> Edit()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> UploadFile(IFormFile file)
        {
            if (file == null || file.Length == 0)
                return Content("file not selected");
            ParseFile(file);
            return RedirectToAction("Index");
        }

        private void ParseFile(IFormFile file)
        {
            var path = Path.Combine(
                        Directory.GetCurrentDirectory(), "wwwroot",
                        "price");

            using (var stream = new FileStream(path, FileMode.Create))
            {
                IExcelDataReader reader;
                reader = ExcelReaderFactory.CreateReader(stream);
                var conf = new ExcelDataSetConfiguration
                {
                    ConfigureDataTable = _ => new ExcelDataTableConfiguration
                    {
                        UseHeaderRow = true
                    }
                };

                var dataSet = reader.AsDataSet(conf);
                var dataTable = dataSet.Tables[0];

                for (var i = 0; i < dataTable.Rows.Count; i++)
                {
                    for (var j = 0; j < dataTable.Columns.Count; j++)
                    {
                        var data = dataTable.Rows[i][j];
                    }
                }
            }
        }

        
    }
}

TrainingApp/TrainingApp.Host/Views/Goods/Edit.cshtml
<form asp-controller="Goods" asp-action="UploadFile" method="post"
      enctype="multipart/form-data">

    <input type="file" name="file" />
    <button type="submit">Upload File</button>
</form> 

TrainingApp/TrainingApp.Host/Views/Goods/Index.cshtml
@model List<TrainingApp.Data.DTO.Goods.GoodsListDTO>

<h2>Список товаров</h2>
@*<a asp-action="Edit" class="btn btn-info navbar-btn"
   data-title="Додати новий проект">
</a>*@
<table class="table">
    <tr>
        <td>
            @Html.DisplayNameFor(model => model[0].Name)
        </td>
        <td>
            @Html.DisplayNameFor(model => model[0].Price)
        </td>
        <td>
            @Html.DisplayNameFor(model => model[0].Count)
        </td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Count)
            </td>
            @*<td>
                <a asp-action="Profile" class="btn btn-info navbar-btn"
                   asp-route-id="@item.Id">
                </a>
            </td>
            <td>
                <a asp-action="Edit" class="btn btn-info navbar-btn"
                   asp-route-id="@item.Id">
                </a>
            </td>
            <td>
                <a asp-action="Delete" class="btn btn-info navbar-btn"
                   asp-route-id="@item.Id">
                </a>
            </td>*@
        </tr>
    }
</table>